#!/usr/bin/php
<?php

// variables
$pwd = realpath( dirname( __FILE__ ) );
$folders = array('fail2ban.d' => 1, 'jail.d' => 1, 'filter.d' => 0, 'action.d' => 0);
$log = '';

checkargs();

function checkargs(){
	global $argv, $log;

	// check fail2ban installation
	if(!is_file('/usr/bin/fail2ban-server') || !is_file('/usr/bin/fail2ban-client')) {
		die("Fail2ban is not installed\n");
	}
	if(!is_dir('/etc/fail2ban')) {
		die("Fail2ban is does not have its configuration in /etc/fail2ban\n");
	}

	if( isset($argv[1]) && strcmp(trim($argv[1]), "update") === 0 ){
		echo "Update code from git repo.\n";
		$log .= `git reset --hard`;
		$log .= `git clean -f`;
		$log .= `git pull`;
		echo "Restart fail2ban\n";
		$log .= `/usr/bin/fail2ban-client restart`;

		echo $log."\n";
		return;
	}

	// get arguments
	echo "Select 1 for Install, 2 for Uninstall, any other key to Abort\n";
	echo "WARNING: fail2filters will empty the fail2ban.d & jail.d folders in your fail2ban configuration folder!\n";

	$handle = fopen("php://stdin","r");
	$option = trim(fgets($handle));
	
	switch($option){
		case 1:
			run(1);
			break;
		case 2:
			run(2);
			break;
		default:
			echo "Aborting ...\n";
			break;
	}
	fclose($handle);
}

function run($option){
	global $log;

	f2f_folders();
	if ($option == 1) { f2f_files(); }
	else { f2f_files(1); }

	echo "Restart fail2ban\n";
	$log .= `/usr/bin/fail2ban-client restart`;

	echo $log."\n";
}

function f2f_list($folder){
	global $pwd;

	if(!is_dir("{$pwd}/{$folder}/")) return array();

	$list = explode("\n", `ls -lah {$pwd}/{$folder}/ |grep ".conf" |awk '{print \$NF}'`);
	array_pop($list);

	return $list;
}

function f2f_folders(){
	global $pwd, $folders, $log;

	foreach($folders as $folder => $delete){
		if($delete){
			echo "Emptying folder /etc/fail2ban/{$folder}\n";
			$log .= `rm -rf /etc/fail2ban/{$folder}/*`;
		}
	}
}

function f2f_files($uninstall = 0){
	global $pwd, $folders, $log;

	foreach($folders as $folder => $delete){
		$list = f2f_list($folder);
		foreach($list as $file){
			echo ($uninstall?"Uninstall":"Install")." {$folder}/{$file}\n";
			$log .= `rm -rf /etc/fail2ban/{$folder}/{$file}`;
			if(!$uninstall) {
				$log .= `cp {$pwd}/{$folder}/{$file} /etc/fail2ban/{$folder}/{$file}`;
			}
		}
	}
}

?>

