#!/usr/bin/php
<?php

// variables
$pwd = realpath( dirname( __FILE__ ) );
$folders = array('fail2ban.d' => 1, 'jail.d' => 1, 'filter.d' => 0, 'action.d' => 0);
$log = '';

// checks & arguments
if(!is_file('/usr/bin/fail2ban-server')) {
	die("Fail2ban is not installed\n");
}
if(!is_dir('/etc/fail2ban')) {
	die("Fail2ban is does not have its configuration in /etc/fail2ban\n");
}

echo "Select 1 for Install, 2 for Uninstall, any other key to Abort\n";
echo "WARINGIN: fail2filters will empty the fail2ban.d & jail.d folders in your fail2ban configuration!\n";

$handle = fopen("php://stdin","r");
$line = fgets($handle);
switch(trim($line)){
	case 1:
		f2f_folders();
		f2f_files();
		break;
	case 2:
		f2f_folders();
		f2f_files(1);
		break;
	default:
		echo "Aborting ...\n";
		break;
}
fclose($handle);
echo $log."\n";
exit;


// functions
function f2f_list($folder){
	global $pwd;

	$list = explode("\n", `ls -lah {$pwd}/{$folder}/ |grep ".conf" |awk '{print \$NF}'`);
	array_pop($list);

	return $list;
}

function f2f_folders(){
	global $pwd, $folders, $log;

	foreach($folders as $folder => $delete){
		if($delete){
			echo "Emptying folder /etc/fail2ban/{$folder}\n";
			$log .= `rm -rf /etc/fail2ban/{$folder}/*`;
		}
	}
}

function f2f_files($uninstall = 0){
	global $pwd, $folders, $log;

	foreach($folders as $folder => $delete){
		$list = f2f_list($folder);
		foreach($list as $file){
			echo ($uninstall?"Uninstall":"Install")." {$folder}/{$file}\n";
			$log .= `rm -rf /etc/fail2ban/{$folder}/{$file}`;
			if(!$uninstall) {
				$log .= `cp {$pwd}/{$folder}/{$file} /etc/fail2ban/{$folder}/{$file}`;
			}
		}
	}

	echo "Restart fail2ban\n";
	$log .= `/bin/systemctl restart fail2ban`;
}

?>

